global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100", "10.0.1.253:9100"]

  - job_name: "linux_tiny"
    static_configs:
      - targets: ["node-exporter:9101", "10.0.1.253:9101"]

  - job_name: "discord_exporter"
    static_configs:
      - targets: ["node-exporter:2112"]
